name: Build and Deploy Spring Boot App to AWS EC2

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1️Checkout Code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2️Set up Java & Maven
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3️Build with Maven
    - name: Build Spring Boot App
      run: mvn clean package

    # 4️Upload Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: springboot-app
        path: target/*.jar

    # 4️Copy JAR to EC2
    - name: Copy JAR to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "target/*.jar"
        target: "/home/ec2-user/app"

    # 5️SSH & Start App Dynamically
    - name: SSH into EC2 & Run Spring Boot App
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Stopping old app process if running..."
          pkill -f 'java -jar' || true
          
          echo "Navigating to app folder..."
          cd /home/ec2-user/app/target
          pwd
          ls
          
          echo "Finding JAR file..."
          JAR_FILE=$(ls *.jar)
          echo "JAR File Found: $JAR_FILE"
          
          echo "Starting new app: $JAR_FILE"
          nohup java -jar VulBankAPI-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          
          echo "Deployment done! "
