name: Build and Deploy Spring Boot App to AWS EC2

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1️Checkout Code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2️Set up Java & Maven
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3️Build with Maven
    - name: Build Spring Boot App
      run: mvn clean package

    # 4️Upload Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: springboot-app
        path: target/*.jar

    # 4️Copy JAR to EC2
    - name: Copy JAR to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "target/*.jar"
        target: "/home/ec2-user/app"

  # 5️SSH & Start App Dynamically
    - name: SSH into EC2 and Deploy
      run: |
        echo "SSH into EC2 and deploying app..."
        ssh -i ${{ secrets.EC2_SSH_KEY_FILE }} -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo " Connected to EC2 Instance"
          
          echo " Current Directory:"
          pwd
          
          echo " Listing Files:"
          ls -l
          
          cd /home/ec2-user/app
          echo "➡ Switched to app folder: $(pwd)"
          
          echo " Files in app folder:"
          ls -l
          
          JAR_FILE=$(ls *.jar)
          echo "Found JAR File: $JAR_FILE"
          
          echo " Killing any old process..."
          pkill -f 'java -jar' || true
          
          echo " Starting Spring Boot app..."
          nohup java -jar "$JAR_FILE" > app.log 2>&1 &
          
          echo " App deployed successfully!"
        EOF
        